<!-- 
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Album</b> and script/action name <b>index</b></p>
</div>
 -->
 
<html>
<head>
<title><?php echo $this->escape($this->title); ?></title>
</head>
<body>
<h1><?php echo $this->escape($this->title); ?></h1>

<p><a href="<?php echo $this->url(array('controller'=>'booklet',
'action'=>'add'));?>">Add new album</a></p>
<table border="1" style="border-collapse: collapse;">
<tr>
<th>Title</th>
<th>Artist</th>
<th>Action</th>
</tr>
<?php foreach($this->albums as $album) : ?>
<tr>
<td><?php echo $this->escape($album->title);?></td>
<td><?php echo $this->escape($album->artist);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'booklet',
'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'booklet',
'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>

</body>
</html>