<!-- <br /><br />
<div id="view-content">
	<p>View script for controller <b>Guestbook</b> and script/action name <b>find</b></p>
</div>
 -->
<p><a href="<?php echo $this->url(
    array(
        'controller' => 'guestbook',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>
 
Guestbook Entries: <br />
<?php if(count($this->entries) > 0){ ?>
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->email) ?></dt>
    <dd><?php echo $this->escape($entry->comment) ?></dd>
    <?php endforeach ?>
</dl>
<?php }else{ ?>
No Data Found!
<?php } ?>